### ISSUE TITLE
Teleporting to overworld

### ISSUE THREAD

**Issue by Dooglamoo** [MCJediYoda/Nether#1]
I think that in the "placeInPortal" method in your Teleporter, you need to find valid coordinates in the overworld to spawn at and set the players position to those coordinates. For example:

BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
BlockPos spawnPos;
for (int y = world.getActualHeight() - 3; y >= 0; y--)
{
        if (!world.isAirBlock(pos.setPos(entityIn.posX, y, entityIn.posZ)))
	{
		spawnPos = new BlockPos(pos.up());
		break;
	}
}
entityIn.setPosition(spawnPos.getX(), spawnPos.getY(), spawnPos.getZ());

**Comment by MCJediYoda** [comment]
Thanks.  This gives me a direction to continue troubleshooting.  Its been driving me crazy.

**Comment by MCJediYoda** [comment]
I figured out the problem.  The teleportation was in the performing effect function so it was constantly trying to teleport to dim 0.  I added a check if dim = -1 then teleport to 0 then cancel the potion.  It works perfectly.  I am still now sure how to do the countdown to teleport the player back to the nether.  I may need a separate method outside of the potion but I wanted the potion to be able to trigger both teleportations.  I will play with it some more and see what I can figure out.

**Comment by MCJediYoda** [comment]
I fixed it.  You can teleport to the overworld using a potion and when the potion duration ends you are teleported back to the nether.  The one thing I still need to work out is how to have random duration between 30 seconds and 5 minutes so you never know how long you are going to get.
